proc import datafile="D:\Database\HRS\RAND HRS 1992-2004.sav" out=HRS_long1 replace;run;
proc import datafile="D:\Database\HRS\RAND HRS 2006-2022.sav" out=HRS_long2 replace;run;
proc import datafile="D:\Database\HRS\Cognition\LangaWeir2022v1\Langa-Weir 1995-2022.sav" out=Langa_Weir replace;run;
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Death\Death 1994-2021.sav" out=Death replace;run;
proc sort data=HRS_long1;by HHID PN;run;
proc sort data=HRS_long2;by HHID PN;run;
proc sort data=Langa_Weir;by HHID PN;run;
proc sort data=Death;by HHID PN;run;

data HRS_base;
merge HRS_long1(in=a keep=HHID PN INW5-INw7 R5AGEY_B R5IWBEG R5SLFMEM R5PSTMEM R5MSTAT R5SMOKEV R5DRINK R5VIGACT R5WORK 
                          R5LBRF R5BMI R5CESD R5CONDE R5SHLT R5IADL5A R5ADL5A R5MOBILA H5ATOTN H5HHRES R6IWBEG R7IWBEG R5ADL6A R5IADL5A R5MOBILA)
      HRS_long2(keep=HHID PN INW8-INW15 RABDATE RAGENDER RAHISPAN RARACEM RAEDUC R8IWBEG R9IWBEG R10IWBEG R11IWBEG R12IWBEG R13IWBEG R14IWBEG R15IWBEG)
      Langa_Weir Death(keep=HHID PN death_date unexpecteddeath deathcause);
by HHID PN;
if a;

if INW5=1;

format birth_date interview_datew5 admin_date YYMMDD10.;
birth_date=RABDATE;
interview_datew5=R5IWBEG;
admin_date='31MAY2021'd;

age=yrdif(birth_date,interview_datew5,'ACT/ACT');
if age ne . and age>=50;

*Cognitive asymmetry;
if cogfunction2000 in (1,2);

if cogfunction2000=1 then obj_problem=0;
else if cogfunction2000=2 then obj_problem=1;

if R5SLFMEM in (1,2,3,4,5) and R5PSTMEM in (1,2,3);
if R5SLFMEM in (4,5) or R5PSTMEM=3 then subj_problem=1;
else if R5SLFMEM in (1,2,3) and R5PSTMEM in (1,2) then subj_problem=0;

length cogmem_grp$40;
if obj_problem=0 and subj_problem=0 then cogmem_grp='Obj Normal; Sub Normal';
else if obj_problem=0 and subj_problem=1 then cogmem_grp='Obj Normal; Sub Problem';
else if obj_problem=1 and subj_problem=0 then cogmem_grp='Obj Problem; Sub Normal';
else if obj_problem=1 and subj_problem=1 then cogmem_grp='Obj Problem; Sub Problem';

*Covariates;
length sex race education marital living_alone smoke drink physicalactivity disease_cat depressive bmi_cat SRH $32;

if RAGENDER=1 then sex='Men';
else if RAGENDER=2 then sex='Women';

if RAHISPAN=1 then race='Hispanic';
else if RAHISPAN=0 and RARACEM=1 then race='Non-Hispanic White';
else if RAHISPAN=0 and RARACEM=2 then race='Non-Hispanic Black';
else if RAHISPAN=0 and RARACEM=3 then race='Non-Hispanic Others';

if RAEDUC in (1,2) then education='<High';
else if RAEDUC=3 then education='High';
else if RAEDUC>=4 then education='>=College';

if H5ATOTN ne . and H5HHRES>0 then asset=H5ATOTN/H5HHRES;

if R5MSTAT in (1,2,3) then marital='Partnered';
else if R5MSTAT in (4,5,6,7,8) then marital='Not partnered';

if H5HHRES=1 then living_alone='Living alone';
else if H5HHRES>1 then living_alone='Not alone';

if R5SMOKEV=1 then smoke='Ever';
else if R5SMOKEV=0 then smoke='Never';

if R5DRINK=1 then drink='Yes';
else if R5DRINK=0 then drink='No';

if R5VIGACT=1 then physicalactivity='Active';
else if R5VIGACT=0 then physicalactivity='Inactive';

BMI=R5BMI;
if BMI ne . then do;
   if BMI<18.5 then bmi_cat='Underweight';
   else if 18.5<=BMI and BMI<25 then bmi_cat='Normal';
   else if 25<=BMI and BMI<30 then bmi_cat='Overweight';
   else if BMI>=30 then bmi_cat='Obese';
end;

if R5CESD>=4 then depressive='Yes';
else if 0<=R5CESD and R5CESD<4 then depressive='No';

disease=R5CONDE;
if disease=0 then disease_cat='0';
else if disease=1 then disease_cat='1';
else if disease>=2 then disease_cat='>=2';

if R5SHLT in (1:3) then SRH='Good';
else if R5SHLT=4 then SRH='Fair';
else if R5SHLT=5 then SRH='Poor';

if asset ne .;
if cmiss(sex,race,education,marital,living_alone,smoke,drink,physicalactivity,disease_cat,depressive,bmi_cat,SRH)=0;



format interview_datew6-interview_datew15 YYMMDD10.;
interview_datew6=R6IWBEG;if INW6=1 and interview_datew6 ne . then agew6=yrdif(birth_date,interview_datew6,'ACT/ACT');
interview_datew7=R7IWBEG;if INW7=1 and interview_datew7 ne . then agew7=yrdif(birth_date,interview_datew7,'ACT/ACT');
interview_datew8=R8IWBEG;if INW8=1 and interview_datew8 ne . then agew8=yrdif(birth_date,interview_datew8,'ACT/ACT');
interview_datew9=R9IWBEG;if INW9=1 and interview_datew9 ne . then agew9=yrdif(birth_date,interview_datew9,'ACT/ACT');
interview_datew10=R10IWBEG;if INW10=1 and interview_datew10 ne . then agew10=yrdif(birth_date,interview_datew10,'ACT/ACT');
interview_datew11=R11IWBEG;if INW11=1 and interview_datew11 ne . then agew11=yrdif(birth_date,interview_datew11,'ACT/ACT');
interview_datew12=R12IWBEG;if INW12=1 and interview_datew12 ne . then agew12=yrdif(birth_date,interview_datew12,'ACT/ACT');
interview_datew13=R13IWBEG;if INW13=1 and interview_datew13 ne . then agew13=yrdif(birth_date,interview_datew13,'ACT/ACT');
interview_datew14=R14IWBEG;if INW14=1 and interview_datew14 ne . then agew14=yrdif(birth_date,interview_datew14,'ACT/ACT');
interview_datew15=R15IWBEG;if INW15=1 and interview_datew15 ne . then agew15=yrdif(birth_date,interview_datew15,'ACT/ACT');

*Death;
format death_date YYMMDD10.;
if death_date ne . and death_date<=admin_date then do;
   new_death=1;
   age_death=yrdif(birth_date,death_date,'ACT/ACT');
end;
else do;
   new_death=0;
   age_death=yrdif(birth_date,admin_date,'ACT/ACT');
end;
time_death=age_death-age;
if time_death<0 then do;
   time_death=0;
   age_death=age;
end;
if time_death=0 then do;
   time_death=0.5;
   age_death=age_death+0.5;
end;

if new_death=1 and unexpecteddeath=1 then new_unexpecteddeath=1;
else if new_death=1 and unexpecteddeath=0 then new_unexpecteddeath=2;
else if new_death=1 and unexpecteddeath=. then new_unexpecteddeath=3;
else if new_death=0 then new_unexpecteddeath=0;
time_unexpecteddeath=time_death;

if new_death=0 then new_deathcause=0;
else if new_death=1 and deathcause in (1,2,3) then new_deathcause=deathcause;
else if new_death=1 then new_deathcause=4;
time_deathcause=time_death;



*Dementia;
array cogf[10] cogfunction2002 cogfunction2004 cogfunction2006 cogfunction2008 cogfunction2010
               cogfunction2012 cogfunction2014 cogfunction2016 cogfunction2018 cogfunction2020;
array cogage[10] agew6 agew7 agew8 agew9 agew10 agew11 agew12 agew13 agew14 agew15;

first_dem_age=.;
last_cog_age=.;

do i=1 to 10;
   if cogf[i] in (1,2,3) and cogage[i] ne . then last_cog_age=cogage[i];
   if cogf[i]=3 and cogage[i] ne . and first_dem_age=. then first_dem_age=cogage[i];
end;

if first_dem_age ne . then do;
   new_dementia=1;
   age_dementia=first_dem_age;
end;
else if new_death=1 then do;
   new_dementia=2;
   age_dementia=age_death;
end;
else if last_cog_age ne . then do;
   new_dementia=0;
   age_dementia=last_cog_age;
end;
else do;
   new_dementia=.;
   age_dementia=.;
end;

if age_dementia ne . then do;
   time_dementia=age_dementia-age;
   if time_dementia<0 then do;
      time_dementia=0;
      age_dementia=age;
   end;
   if time_dementia=0 then do;
      time_dementia=0.5;
      age_dementia=age_dementia+0.5;
   end;
end;

if new_dementia=. then delete;



*Early-onset dementia and premature death;
if age<60 then do;

   *Premature death before age 65;
   if new_death=1 and age_death<65 then do;
      new_earlydeath=1;
      age_earlydeath=age_death;
   end;
   else do;
      new_earlydeath=0;
      age_earlydeath=65;
   end;

   time_earlydeath=age_earlydeath-age;
   if time_earlydeath<0 then do;
      time_earlydeath=0;
      age_earlydeath=age;
   end;
   if time_earlydeath=0 then do;
      time_earlydeath=0.5;
      age_earlydeath=age_earlydeath+0.5;
   end;

   *Early-onset dementia before age 65;
   if first_dem_age ne . and first_dem_age<65 then do;
      new_earlydementia=1;
      age_earlydementia=first_dem_age;
   end;
   else if new_death=1 and age_death<65 then do;
      new_earlydementia=2;
      age_earlydementia=age_death;
   end;
   else do;
      new_earlydementia=0;
      if last_cog_age ne . then age_earlydementia=min(last_cog_age,65);
      else age_earlydementia=65;
   end;

   time_earlydementia=age_earlydementia-age;
   if time_earlydementia<0 then do;
      time_earlydementia=0;
      age_earlydementia=age;
   end;
   if time_earlydementia=0 then do;
      time_earlydementia=0.5;
      age_earlydementia=age_earlydementia+0.5;
   end;
end;
run;

proc rank data=HRS_base groups=3 out=asset_ranked;
var asset;
ranks asset_rank;
run;

data HRS_final;
set asset_ranked;
length tertile_asset $20;
if asset_rank=0 then tertile_asset='Low';
else if asset_rank=1 then tertile_asset='Middle';
else if asset_rank=2 then tertile_asset='High';
run;

proc freq data=HRS_final;
tables cogmem_grp new_dementia new_death new_unexpecteddeath new_deathcause new_earlydementia new_earlydeath SRH/missing;
run;

proc means data=HRS_final n mean std min max;
class new_dementia;
var time_dementia age_dementia;
run;

%let class=sex race education tertile_asset marital living_alone smoke drink physicalactivity bmi_cat disease_cat depressive SRH;
%let covariate=age sex race education tertile_asset marital living_alone smoke drink physicalactivity bmi_cat disease_cat depressive SRH;

*Dementia;
proc freq data=HRS_final;
table new_dementia;
run;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;

proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp|age &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
proc freq data=HRS_final;
where age<60;
table new_dementia;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where 60<=age<70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age>=70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;



*Death;
proc freq data=HRS_final;
table new_death;
run;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_death*new_death(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;

proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_death*new_death(0)=cogmem_grp|age &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc freq data=HRS_final;
where age>=70;
table new_death;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_death*new_death(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where 60<=age<70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_death*new_death(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age>=70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_death*new_death(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;



*Cancer death;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp|age &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where 60<=age<70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age>=70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;

*CVD death;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp|age &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where 60<=age<70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age>=70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;

*Other death;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp|age &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where 60<=age<70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age>=70;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;



*Early-onset dementia;
proc freq data=HRS_final;
where age<60;
table cogmem_grp*new_earlydementia;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_earlydementia*new_earlydementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
*Premature death;
proc freq data=HRS_final;
where age<60;
table cogmem_grp*new_earlydeath;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model time_earlydeath*new_earlydeath(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;



*Vs. Obj Problem Sub Problem;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_dementia*new_dementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_death*new_death(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_deathcause*new_deathcause(0,2,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_deathcause*new_deathcause(0,1,3,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_deathcause*new_deathcause(0,1,2,4)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_earlydementia*new_earlydementia(0)=cogmem_grp &covariate/rl eventcode=1;
ods select ParameterEstimates;
run;
proc phreg data=HRS_final;
where age<60;
class cogmem_grp(ref='Obj Problem; Sub Problem') &class/param=ref;
model time_earlydeath*new_earlydeath(0)=cogmem_grp &covariate/rl ties=efron;
ods select ParameterEstimates;
run;



*HCAP Domain-specific cognition;
proc import datafile="D:\Database\HRS\HCAP\HC16summary\HC16HP_F.sav" out=HCAP_summary replace;run;
proc sort data=HRS_final;by HHID PN;run;
proc sort data=HCAP_summary;by HHID PN;run;
data HCAP_summary2;
set HCAP_summary;
/* PV-based HRS-HCAP factor scores: mean=50, SD=10 in the HRS-HCAP sample */
hcap_gcp_z=(vs5gcp_pv-50)/10;
hcap_mem_z=(vs4mem_pv-50)/10;
hcap_exf_z=(vs4exf_pv-50)/10;
hcap_lfl_z=(vs4lfl_pv-50)/10;
if cmiss(hcap_gcp_z,hcap_mem_z,hcap_exf_z,hcap_lfl_z)=0;
keep HHID PN vs5gcp_pv vs4mem_pv vs4exf_pv vs4lfl_pv hcap_gcp_z hcap_mem_z hcap_exf_z hcap_lfl_z;
run;
proc means data=HCAP_summary2 n mean std min max;
var hcap_gcp_z hcap_mem_z hcap_exf_z hcap_lfl_z;
run;
data HRS_HCAP;
merge HRS_final(in=a) HCAP_summary2(in=b);
by HHID PN;
if a and b;
run;
*HCAP global cognitive performance;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_gcp_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_gcp_z=cogmem_grp|age &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_HCAP;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_gcp_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_gcp_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
*HCAP memory;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_mem_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_mem_z=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_mem_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_mem_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
*HCAP executive function;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_exf_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_exf_z=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_exf_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_exf_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
*HCAP language and fluency;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_lfl_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_lfl_z=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_lfl_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HCAP;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hcap_lfl_z=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;



/*VBS/HCAP Biopilot Biomarker*/
proc import datafile="D:\Database\HRS\Biomarker or genetic\VBS 2016\HCAPbioPilot\hcapbiopilota_r.sav" out=hcapbiopilot dbms=sav replace;run;
proc import datafile="D:\Database\HRS\Biomarker or genetic\VBS 2016\HRS_VBS.sav" out=VBS dbms=sav replace;run;
data blood;
set hcapbiopilot;
if pabeta42>0 then AB42=log(pabeta42);
if pabeta40>0 then AB40=log(pabeta40);
if pab42_40_ratio ne . then AB42_40_ratio=pab42_40_ratio;
if pgfap>0 then GFAP=log(pgfap);
if pptau181>0 then ptau181=log(pptau181);
if pnfl>0 then NfL=log(pnfl);
keep HHID PN AB42 AB40 AB42_40_ratio GFAP ptau181 NfL;
run;
proc sort data=HRS_final;by HHID PN;run;
proc sort data=blood;by HHID PN;run;
proc sort data=VBS;by HHID PN;run;
data HRS_blood1;
merge HRS_final(in=a) blood(in=b) VBS(in=c keep=HHID PN PCR PCYSC);
by HHID PN;
if a and b and c;
if PCR>0 then creatinine=log(PCR);
if PCYSC>0 then CystatinC=log(PCYSC);
if nmiss(AB42,AB40,AB42_40_ratio,GFAP,ptau181,NfL,creatinine,CystatinC)=0;
run;
proc standard data=HRS_blood1 mean=0 std=1 out=HRS_blood;
var AB42 AB40 AB42_40_ratio GFAP ptau181 NfL creatinine CystatinC;
run;
proc means data=HRS_blood;
var AB42 AB40 AB42_40_ratio GFAP ptau181 NfL creatinine CystatinC;
run;
%let class=sex race education tertile_asset marital living_alone smoke drink physicalactivity bmi_cat disease_cat depressive SRH;
%let covariate=age sex race education tertile_asset marital living_alone smoke drink physicalactivity bmi_cat disease_cat depressive SRH;
*AB42;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
*AB40;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB40=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB40=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB40=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB40=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
*AB42_40_ratio;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42_40_ratio=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42_40_ratio=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42_40_ratio=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model AB42_40_ratio=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
*GFAP;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model GFAP=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model GFAP=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model GFAP=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model GFAP=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
*ptau181;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model ptau181=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model ptau181=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model ptau181=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model ptau181=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
*NfL;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model NfL=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model NfL=cogmem_grp|age creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model NfL=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;
proc genmod data=HRS_blood;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model NfL=cogmem_grp creatinine CystatinC &covariate/dist=normal link=identity;
run;



/*Subjective/perceived aging*/
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Aging\SAAccel.sav" out=SAAccel dbms=sav replace;run;
proc sort data=HRS_final;by HHID PN;run;
proc sort data=SAAccel;by HHID PN;run;
data HRS_SAAccel;
merge HRS_final(in=a) SAAccel(in=b);
by HHID PN;
if a and b;
if SAAccel ne .;
run;
proc means data=HRS_SAAccel n mean std min max;
var SAAccel;
run;
proc means data=HRS_SAAccel n mean std;
class cogmem_grp;
var SAAccel;
run;
proc genmod data=HRS_SAAccel;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model SAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_SAAccel;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model SAAccel=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_SAAccel;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model SAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_SAAccel;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model SAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

/*Clinical biomarker-based biological aging*/
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Aging\BAAccel.sav" out=BAAccel dbms=sav replace;run;
proc sort data=BAAccel;by HHID PN;run;
data HRS_BAAccel;
merge HRS_final(in=a) BAAccel(in=b);
by HHID PN;
if a and b;
if nmiss(KDMBAAccel,PhenoAgeAccel,hd_log)<3;
run;
proc means data=HRS_BAAccel n mean std min max;
var KDMBAAccel PhenoAgeAccel hd_log;
run;
proc means data=HRS_BAAccel n mean std;
class cogmem_grp;
var KDMBAAccel PhenoAgeAccel hd_log;
run;
*KDM biological age acceleration;
proc genmod data=HRS_BAAccel;
where KDMBAAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model KDMBAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where KDMBAAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model KDMBAAccel=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age<65 and KDMBAAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model KDMBAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age>=65 and KDMBAAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model KDMBAAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Phenotypic age acceleration;
proc genmod data=HRS_BAAccel;
where PhenoAgeAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model PhenoAgeAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where PhenoAgeAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model PhenoAgeAccel=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age<65 and PhenoAgeAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model PhenoAgeAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age>=65 and PhenoAgeAccel ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model PhenoAgeAccel=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Homeostatic dysregulation;
proc genmod data=HRS_BAAccel;
where hd_log ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hd_log=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where hd_log ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hd_log=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age<65 and hd_log ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hd_log=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_BAAccel;
where age>=65 and hd_log ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model hd_log=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

/*Physiological pace of aging*/
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Aging\HRSPoA.sav" out=HRSPoA dbms=sav replace;run;
proc sort data=HRSPoA;by HHID PN;run;
data HRS_HRSPoA;
merge HRS_final(in=a) HRSPoA(in=b);
by HHID PN;
if a and b;
if HRSPoA ne .;
run;
proc means data=HRS_HRSPoA n mean std min max;
var HRSPoA;
run;
proc means data=HRS_HRSPoA n mean std;
class cogmem_grp;
var HRSPoA;
run;
proc genmod data=HRS_HRSPoA;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model HRSPoA=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HRSPoA;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model HRSPoA=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HRSPoA;
where age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model HRSPoA=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_HRSPoA;
where age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model HRSPoA=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

/*DNA methylation-based epigenetic aging*/
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Aging\EAA.sav" out=EAA dbms=sav replace;run;
proc sort data=EAA;by HHID PN;run;
data HRS_EAA;
merge HRS_final(in=a) EAA(in=b);
by HHID PN;
if a and b;
if nmiss(EAA_Horvath1,EAA_Hannum,EAA_Zhang,EAA_Levine,EAA_GrimAge2,DunedinPACE)<6;
run;
proc means data=HRS_EAA n mean std min max;
var EAA_Horvath1 EAA_Hannum EAA_Zhang EAA_Levine EAA_GrimAge2 DunedinPACE;
run;
proc means data=HRS_EAA n mean std;
class cogmem_grp;
var EAA_Zhang EAA_Levine EAA_GrimAge2 DunedinPACE EAA_Horvath1 EAA_Hannum;
run;

*Horvath clock acceleration;
proc genmod data=HRS_EAA;
where EAA_Horvath1 ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Horvath1=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Horvath1 ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Horvath1=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Horvath1 ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Horvath1=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Horvath1 ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Horvath1=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Hannum clock acceleration;
proc genmod data=HRS_EAA;
where EAA_Hannum ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Hannum=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Hannum ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Hannum=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Hannum ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Hannum=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Hannum ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Hannum=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Zhang mortality clock acceleration;
proc genmod data=HRS_EAA;
where EAA_Zhang ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Zhang=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Zhang ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Zhang=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Zhang ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Zhang=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Zhang ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Zhang=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*DNAm PhenoAge acceleration;
proc genmod data=HRS_EAA;
where EAA_Levine ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Levine=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Levine ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Levine=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Levine ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Levine=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_Levine ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_Levine=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*GrimAge2 acceleration;
proc genmod data=HRS_EAA;
where EAA_GrimAge2 ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_GrimAge2=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_GrimAge2 ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_GrimAge2=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_GrimAge2 ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_GrimAge2=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where EAA_GrimAge2 ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model EAA_GrimAge2=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*DunedinPACE acceleration;
proc genmod data=HRS_EAA;
where DunedinPACE ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model DunedinPACE=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where DunedinPACE ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model DunedinPACE=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where DunedinPACE ne . and age<65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model DunedinPACE=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_EAA;
where DunedinPACE ne . and age>=65;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model DunedinPACE=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

/*RNA-based cellular senescence*/
proc import datafile="D:\AAA Ongoing Projects\Cognitive discordance\Results\Aging\AgingRNA.sav" out=AgingRNA dbms=sav replace;run;
proc sort data=AgingRNA;by HHID PN;run;
proc sort data=HRS_final;by HHID PN;run;
proc means data=AgingRNA n mean std min max;
var z_score_CSP z_score_CellAge z_score_Dunkley z_score_GO z_score_Garcia z_score_KEGG z_score_SIP z_score_SRP z_score_SenMayo z_score_SenescenceSummary;
run;
proc standard data=AgingRNA mean=0 std=1 out=AgingRNA2;
var z_score_CSP z_score_CellAge z_score_Dunkley z_score_GO z_score_Garcia z_score_KEGG z_score_SIP z_score_SRP z_score_SenMayo z_score_SenescenceSummary;
run;
data HRS_AgingRNA;
merge HRS_final(in=a) AgingRNA2(in=b);
by HHID PN;
if a and b;
run;
proc means data=HRS_AgingRNA n mean std min max;
var z_score_CSP z_score_CellAge z_score_Dunkley z_score_GO z_score_Garcia z_score_KEGG z_score_SIP z_score_SRP z_score_SenMayo z_score_SenescenceSummary;
run;
proc means data=HRS_AgingRNA n mean std;
class cogmem_grp;
var z_score_CSP z_score_CellAge z_score_Dunkley z_score_GO z_score_Garcia z_score_KEGG z_score_SIP z_score_SRP z_score_SenMayo z_score_SenescenceSummary;
run;

*Canonical senescence pathway;
proc genmod data=HRS_AgingRNA;
where z_score_CSP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CSP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_CSP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CSP=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_CSP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CSP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_CSP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CSP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Senescence initiating pathway;
proc genmod data=HRS_AgingRNA;
where z_score_SIP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SIP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_SIP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SIP=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_SIP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SIP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_SIP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SIP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Senescence response pathway;
proc genmod data=HRS_AgingRNA;
where z_score_SRP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SRP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_SRP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SRP=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_SRP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SRP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_SRP ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SRP=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Senescence summary score;
proc genmod data=HRS_AgingRNA;
where z_score_SenescenceSummary ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenescenceSummary=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_SenescenceSummary ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenescenceSummary=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_SenescenceSummary ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenescenceSummary=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_SenescenceSummary ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenescenceSummary=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*SenMayo score;
proc genmod data=HRS_AgingRNA;
where z_score_SenMayo ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenMayo=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_SenMayo ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenMayo=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_SenMayo ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenMayo=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_SenMayo ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_SenMayo=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*CellAge score;
proc genmod data=HRS_AgingRNA;
where z_score_CellAge ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CellAge=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_CellAge ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CellAge=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_CellAge ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CellAge=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_CellAge ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_CellAge=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Dunkley score;
proc genmod data=HRS_AgingRNA;
where z_score_Dunkley ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Dunkley=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_Dunkley ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Dunkley=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_Dunkley ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Dunkley=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_Dunkley ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Dunkley=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*GO score;
proc genmod data=HRS_AgingRNA;
where z_score_GO ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_GO=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_GO ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_GO=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_GO ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_GO=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_GO ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_GO=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*Garcia score;
proc genmod data=HRS_AgingRNA;
where z_score_Garcia ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Garcia=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_Garcia ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Garcia=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_Garcia ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Garcia=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_Garcia ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_Garcia=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;

*KEGG score;
proc genmod data=HRS_AgingRNA;
where z_score_KEGG ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_KEGG=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where z_score_KEGG ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_KEGG=cogmem_grp|age &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age<65 and z_score_KEGG ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_KEGG=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
proc genmod data=HRS_AgingRNA;
where age>=65 and z_score_KEGG ne .;
class cogmem_grp(ref='Obj Normal; Sub Normal') &class/param=ref;
model z_score_KEGG=cogmem_grp &covariate/dist=normal link=identity;
ods select ParameterEstimates;
run;
